DATA:
  TEST:
    DATALOADER:
      KWARGS:
        batch_size: 4
        num_workers: 2
    DATASET:
      KWARGS:
        fingers:
          - f1
          - f2
          - f3
          - f4
        frames_per_video: 2
        gallery_movements:
          - Roll
          - Pitch
          - Yaw
        mode: test
        probe_movements:
          - Pitch
        root: &root "D:/workspace/datasets/MMFV-25th"
        segment: &segment true
        subjects: test.txt
      NAME: MMFVSingle
  TRAIN:
    DATALOADER:
      KWARGS:
        batch_size: 8
        num_workers: 4
    DATASET:
      KWARGS:
        fingers: &fingers
          - f1
          - f2
          - f3
          - f4
        gallery_movements: &movements
          - Roll
          - Pitch
          - Yaw
        mode: train
        probe_movements: *movements
        root: *root
        segment: *segment
        subjects: train.txt
      NAME: MMFVContrastive
  VAL:
    DATALOADER:
      KWARGS:
        batch_size: 4
        num_workers: 2
    DATASET:
      KWARGS:
        fingers: *fingers
        frames_per_video: 2
        gallery_movements:
          - Roll
          - Pitch
          - Yaw
        mode: val
        probe_movements:
          - Pitch
        root: *root
        segment: *segment
        subjects: test.txt
      NAME: MMFVSingle
EVALUATOR:
  TEST:
    KWARGS:
      fusion: "feat-avg"
      verbose: true
    NAME: FingerprintEvaluator
  VAL:
    KWARGS:
      fusion: "feat-avg"
      verbose: false
    NAME: FingerprintEvaluator
INPUT:
  IMAGE:
    IMG_SIZE: &img_size [ 384, 384 ]
    MEAN: [ 0.4850, 0.4560, 0.4060 ]
    STD: [ 0.2290, 0.2240, 0.2250 ]
LOSSES:
  - NAME: "VICRegLoss"
    WEIGHT: 0.5
    KWARGS:
      sim_coeff: 25.0
      std_coeff: 25.0
      cov_coeff: 1.0
  - NAME: "CrossCosineEmbeddingLoss"
    WEIGHT: 0.5
    KWARGS:
      pos_wt: 1.0
      neg_wt: 1.0
MODEL:
  META_ARCH:
    NAME: "Contrastive"
  BACKBONE:
    NAME: "swin_base_patch4_window12_384.ms_in22k_ft_in1k"
    KWARGS:
      img_size: *img_size
      pretrained: True
      num_classes: &dim 256 # feature size
  HEAD:
    NAME: "Identity"
OPTIM:
  OPTIMIZER:
    NAME: "LARS"
    KWARGS:
      lr: 0.001
      weight_decay: 0.000001
  LR_SCHEDULERS:
    SCHEDULERS:
      - NAME: "LinearLR"
        KWARGS:
          start_factor: 0.1
          total_iters: &iters1 500
      - NAME: "CosineAnnealingLR"
        KWARGS:
          T_max: 9500
    MILESTONES:
      - *iters1
PARAMS:
  ITERS: 10000
  SAVE_EVERY: 200
  PRINT_EVERY: 1
  EVAL_EVERY: 200