DATA:
  TEST:
    DATALOADER:
      KWARGS:
        batch_size: 8
        num_workers: 4
    DATASET:
      KWARGS:
        fingers: &fingers
        - f1
        - f2
        - f3
        - f4
        movements: &movements
        - Roll
        - Pitch
        - Yaw
        root: &root "D:/workspace/datasets/MMFV-25th"
        mode: "test"
        subjects: test.txt
      NAME: MMFVContrastive
  TRAIN:
    DATALOADER:
      KWARGS:
        batch_size: 8
        num_workers: 4
    DATASET:
      KWARGS:
        fingers: *fingers
        movements: *movements
        root: *root
        mode: "train"
        subjects: train.txt
      NAME: MMFVContrastive
  VAL:
    DATALOADER:
      KWARGS:
        batch_size: 8
        num_workers: 4
    DATASET:
      KWARGS:
        fingers: *fingers
        movements: *movements
        root: *root
        mode: "val"
        subjects: test.txt
      NAME: MMFVContrastive
INPUT:
  IMAGE:
    IMG_SIZE: &img_size [ 384, 384 ]
    TRAIN_MAX_SIZE: [320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280]
    MEAN: [ 0.4850, 0.4560, 0.4060 ]
    STD: [ 0.2290, 0.2240, 0.2250 ]
LOSS:
  NAME: "VICReg"
  KWARGS:
    sim_coeff: 25.0
    std_coeff: 25.0
    cov_coeff: 1.0
MODEL:
  META_ARCH:
    NAME: "Contrastive"
  BACKBONE:
    NAME: "swin_base_patch4_window12_384.ms_in22k_ft_in1k"
    KWARGS:
      img_size: *img_size
      pretrained: True
      num_classes: &dim 256 # feature size
  HEAD:
    NAME: "Identity"
#  HEAD:
#    NAME: "Expander"
#    KWARGS:
#      in_channels: *dim
#      out_channels: 128
OPTIM:
  OPTIMIZER:
    NAME: "LARS"
    KWARGS:
      lr: 0.001
      weight_decay: 0.000001
  LR_SCHEDULERS:
    SCHEDULERS:
      - NAME: "LinearLR"
        KWARGS:
          start_factor: 0.1
          total_iters: &iters1 500
      - NAME: "CosineAnnealingLR"
        KWARGS:
          T_max: 9500
    MILESTONES:
      - *iters1
PARAMS:
  ITERS: 10000
  SAVE_EVERY: 200
  PRINT_EVERY: 1
  EVAL_EVERY: 200