DATA:
  ROOT: &root "D:/workspace/datasets/MMFV-25th"
  TEST:
    DATALOADER:
      KWARGS:
        batch_size: 4
        num_workers: 2
        shuffle: false
    DATASET:
      KWARGS:
        root: *root
        crop: &crop true
        segment: &segment true
        hist: &hist true
        frames_per_video: 2
        fingers: &fingers [f1, f2, f3, f4]
        gallery_movements: &all_movements [Roll, Pitch, Yaw]
        probe_movements:
          - Pitch
        mode: test
        randomize: true
        subjects: test.txt
      NAME: MMFVSingle
  TRAIN:
    DATALOADER:
      KWARGS:
        batch_size: 8
        num_workers: 4
        shuffle: true
    DATASET:
      KWARGS:
        root: *root
        crop: *crop
        segment: *segment
        hist: *hist
        frames_per_video: null
        fingers: *fingers
        gallery_movements: *all_movements
        probe_movements: *all_movements
        mode: train
        randomize: true
        subjects: train.txt
      NAME: MMFVContrastive
  VAL:
    DATALOADER:
      KWARGS:
        batch_size: 4
        num_workers: 2
        shuffle: false
    DATASET:
      KWARGS:
        root: *root
        crop: *crop
        segment: *segment
        hist: *hist
        frames_per_video: 2
        fingers: *fingers
        gallery_movements: *all_movements
        probe_movements:
          - Roll
        mode: val
        randomize: false
        subjects: val.txt
      NAME: MMFVContrastive
EVALUATOR:
  TEST:
    KWARGS:
      fusion: "feat-avg"
      verbose: true
    NAME: FingerprintEvaluator
  VAL:
    KWARGS:
      fusion: "feat-avg"
      verbose: false
    NAME: FingerprintEvaluator
INPUT:
  IMAGE:
    IMG_SIZE: &img_size [ 384, 384 ]
    MEAN: [ 0.4850, 0.4560, 0.4060 ]
    STD: [ 0.2290, 0.2240, 0.2250 ]
    BINARY: false
LOSSES:
  - NAME: "VICRegLoss"
    WEIGHT: 0.05
    KWARGS:
      sim_coeff: 25.0
      std_coeff: 25.0
      cov_coeff: 1.0
  - NAME: "CrossCosineEmbeddingLoss"
    WEIGHT: 0.95
    KWARGS:
      pos_wt: 1.0
      neg_wt: 1.0
  - NAME: "FocalLoss"
    WEIGHT: 1.00
    KWARGS:
      alpha: 0.25
      gamma: 2
      reduction: "mean"
MODEL:
  META_ARCH:
    NAME: "Contrastive"
  BACKBONE:
    NAME: "swin_base_patch4_window12_384.ms_in22k_ft_in1k"
    KWARGS:
      img_size: *img_size
      pretrained: True
      num_classes: &dim 256 # feature size
  HEAD:
    NAME: "Identity"
  CLASSIFIER:
    KWARGS:
      channels:
        - 512
        - 64
        - 8
        - 1
    NAME: BinaryClassifier
OPTIM:
  OPTIMIZER:
    NAME: "LARS"
    KWARGS:
      lr: 0.01
      weight_decay: 0.000001
  LR_SCHEDULERS:
    SCHEDULERS:
      - NAME: "LinearLR"
        KWARGS:
          start_factor: 0.1
          total_iters: &iters1 500
      - NAME: "CosineAnnealingLR"
        KWARGS:
          T_max: 9500
    MILESTONES:
      - *iters1
PARAMS:
  ITERS: 10000
  SAVE_EVERY: 200
  PRINT_EVERY: 10
  EVAL_EVERY: 200