DATA:
  ROOT: &root "D:/workspace/datasets/MMFV-25th"
  TEST:
    DATALOADER:
      KWARGS:
        batch_size: 4
        num_workers: 2
        shuffle: false
    DATASET:
      KWARGS:
        root: *root
        crop: &crop true
        segment: &segment true
        hist: &hist true
        frames_per_video: 2
        fingers: &fingers
          - f1
          - f2
          - f3
          - f4
        gallery_movements: &all_movements
          - Roll
          - Pitch
          - Yaw
        probe_movements:
          - Pitch
        mode: test
        randomize: true
        subjects: test.txt
      NAME: MMFVSingle
  TRAIN:
    DATALOADER:
      KWARGS:
        batch_size: 8
        num_workers: 4
        shuffle: true
    DATASET:
      KWARGS:
        root: *root
        crop: *crop
        segment: *segment
        hist: *hist
        frames_per_video: 2
        fingers: *fingers
        gallery_movements: *all_movements
        probe_movements: *all_movements
        mode: train
        randomize: true
        subjects: train.txt
      NAME: MMFVContrastive
  VAL:
    DATALOADER:
      KWARGS:
        batch_size: 4
        num_workers: 2
        shuffle: false
    DATASET:
      KWARGS:
        root: *root
        crop: *crop
        segment: *segment
        hist: *hist
        frames_per_video: 2
        fingers: *fingers
        gallery_movements: *all_movements
        probe_movements:
          - Roll
        mode: val
        randomize: false
        subjects: val.txt
      NAME: MMFVContrastive
