DATA:
  TEST:
    DATALOADER:
      KWARGS:
        batch_size: 4
        num_workers: 2
    DATASET:
      KWARGS:
        fingers:
          - f1
          - f2
          - f3
          - f4
        frames_per_video: 2
        gallery_movements:
          - Roll
          - Pitch
          - Yaw
        probe_movements:
          - Pitch
        root: &root "D:/workspace/datasets/MMFV-25th"
        segment: &segment true
        subjects: test.txt
      NAME: MMFVSingle
  TRAIN:
    DATALOADER:
      KWARGS:
        batch_size: 8
        num_workers: 4
    DATASET:
      KWARGS:
        fingers: &fingers
          - f1
          - f2
          - f3
          - f4
        mode: "train"
        gallery_movements: &movements
          - Roll
          - Pitch
          - Yaw
        probe_movements: *movements
        root: *root
        segment: *segment
        subjects: train.txt
      NAME: MMFVContrastive
  VAL:
    DATALOADER:
      KWARGS:
        batch_size: 4
        num_workers: 2
    DATASET:
      KWARGS:
        fingers: *fingers
        frames_per_video: 2
        gallery_movements:
          - Roll
          - Pitch
          - Yaw
        mode: val
        probe_movements:
          - Pitch
        root: *root
        segment: *segment
        subjects: test.txt
      NAME: MMFVSingle
EVALUATOR:
  TEST:
    KWARGS:
      fusion: "feat-avg"
      verbose: true
    NAME: FingerprintEvaluator
  VAL:
    KWARGS:
      fusion: "feat-avg"
      verbose: false
    NAME: FingerprintEvaluator