DATA:
  TEST:
    DATALOADER:
      KWARGS:
        batch_size: 2
        num_workers: 2
    DATASET:
      KWARGS:
        fingers:
          - f1
          - f2
          - f3
          - f4
        gallery_movements:
          - Roll
          - Pitch
          - Yaw
        probe_movements:
          - Pitch
        root: &root "D:/workspace/datasets/MMFV-25th"
        segment: &segment true
        subjects: test.txt
      NAME: MMFVEval
  TRAIN:
    DATALOADER:
      KWARGS:
        batch_size: 8
        num_workers: 4
    DATASET:
      KWARGS:
        fingers: &fingers
          - f1
          - f2
          - f3
          - f4
        movements: &movements
          - Roll
          - Pitch
          - Yaw
        root: *root
        mode: "train"
        segment: *segment
        subjects: train.txt
      NAME: MMFVContrastive
  VAL:
    DATALOADER:
      KWARGS:
        batch_size: 8
        num_workers: 4
    DATASET:
      KWARGS:
        fingers: *fingers
        movements: *movements
        mode: "val"
        root: *root
        segment: *segment
        subjects: test.txt
      NAME: MMFVContrastive
