LOSSES:
- KWARGS:
    cov_coeff: 0.01
    sim_coeff: 1.0
    std_coeff: 1.0
  NAME: VICRegLoss
  WEIGHT: 1.0
- KWARGS:
    margin: 0.0
    neg_wt: 0.50
    pos_wt: 1.50
    reduction: dynamic
  NAME: CrossCosineEmbeddingLoss
  WEIGHT: 1.0
