LOSSES:
- KWARGS:
    cov_coeff: 0.01
    sim_coeff: 1.0
    std_coeff: 1.0
  NAME: VICRegLoss
  WEIGHT: 1.0
- KWARGS:
    alpha: 0.25
    gamma: 2
    reduction: dynamic
  NAME: FocalLoss
  WEIGHT: 1.0
