LOSSES:
  - NAME: "VICRegLoss"
    WEIGHT: 0.10
    KWARGS:
      sim_coeff: 25.0
      std_coeff: 25.0
      cov_coeff: 1.0
  - NAME: "CrossCosineEmbeddingLoss"
    WEIGHT: 0.5
    KWARGS:
      pos_wt: 1.75
      neg_wt: 0.25
OPTIM:
  OPTIMIZER:
    NAME: "Adam"
    KWARGS:
      lr: 0.001
      weight_decay: 0.000001
  LR_SCHEDULERS:
    SCHEDULERS:
      - NAME: "LinearLR"
        KWARGS:
          start_factor: 0.1
          total_iters: &iters1 500
      - NAME: "CosineAnnealingLR"
        KWARGS:
          T_max: 9500
    MILESTONES:
      - *iters1
PARAMS:
  ITERS: 10000
  SAVE_EVERY: 200
  PRINT_EVERY: 5
  EVAL_EVERY: 200