MODEL:
  BACKBONE:
    KWARGS:
      in_chans: 3
      num_classes: 512
      pretrained: true
    NAME: resnet50.a1_in1k
  CLASSIFIER:
    KWARGS:
      channels:
      - 1024
      - 128
      - 1
    NAME: BinaryClassifier
  EXPANDER:
    KWARGS:
      in_channels: 512
      out_channels: 8192
    NAME: Expander
  HEAD:
    NAME: Identity
  META_ARCH:
    NAME: Contrastive
INPUT:
  IMAGE:
    BINARY: false
    IMG_SIZE:
    - 224
    - 224
    MEAN:
    - 0.485
    - 0.456
    - 0.406
    STD:
    - 0.229
    - 0.224
    - 0.225