INPUT:
  IMAGE:
    IMG_SIZE: &img_size [ 384, 384 ]
    TRAIN_MAX_SIZE: [320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280]
    MEAN: [ 0.4850, 0.4560, 0.4060 ]
    STD: [ 0.2290, 0.2240, 0.2250 ]
MODEL:
  META_ARCH:
    NAME: "Contrastive"
  BACKBONE:
    NAME: "swin_base_patch4_window12_384.ms_in22k_ft_in1k"
    KWARGS:
      img_size: *img_size
      pretrained: True
      num_classes: &dim 256 # feature size
  HEAD:
    NAME: "Identity"
